### ISSUE TITLE
Due to the index of refraction discontinuity at the surface有什么好的解释么？

### ISSUE THREAD

**Issue by LinkClinton** [LinkClinton/IGP-DirectX12-Chinese#8]
物理太弱，这一句话不知道他在指的什么。有dalao有什么好的解释么？

**Comment by lijipeng787** [comment]
index of refraction discontinuity 可以翻译为折射不连续性系数，应该是光学里的某种专业术语，但是baidu不到完全与其符合的名称。晚上回家试试google吧。
在网上查到了另一种解释：“ If one thing is an index of another, it indicates what the other thing will be like“。推测可以翻译为：“由于在表面产生的不连续折射现象......”或“由于物体表面的折射不连续性......”。
这句话在原书哪一部分？结合上下文再看看吧。

**Comment by LinkClinton** [comment]
翻译上确实是这个意思没错。主要不理解的是它所具体描述的意义。段落内容我记得是在第8章的第7节左右，关于镜面光和漫反射光部分。手机没法具体指出哪里qaq

**Comment by LinkClinton** [comment]
翻译上确实是这个意思没错。主要不理解的是它所具体描述的意义。段落内容我记得是在第8章的第7节左右，关于镜面光和漫反射光部分。手机没法具体指出哪里qaq

**Comment by lijipeng787** [comment]
“Let us consider a flat surface with normal n that separates two mediums with
different indices of refraction. Due to the index of refraction discontinuity at the surface, when incoming light strikes the surface some reflects away from the surface and some refracts into the surface”
这是我在原文找到的最相似的段落，不知道是否是你询问的那一段。
我的翻译如下：”我们设想这样一种情况，有一个法线为n的平面将折射率不同的两种（能供传输光的）媒介分隔开。由于在该平面上折射率不连续，所以当一束光线照射到该平面时，一部分光被反射掉而另一部分直接射入平面内。“

**Comment by LinkClinton** [comment]
对，是这一段。
大概知道了，我以为他说的折射率不连续时指另外的意思。
它说的不连续我当场就懵逼了，但是你翻译后我大概就知道它说的不连续其实就是说不同了QAQ，思想僵化啊。
